version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping lambda functions from gtihub..."
      - zip -r9 lf1.zip lambda_function_1.py
      - zip -r9 lf2.zip lambda_function_1.py
  post_build:
    commands:
      - echo "Updating lambda Functions..."
      - aws lambda update-function-code --function-name lf1-assignment-2 --zip-file fileb://lf1.zip
      - aws lambda update-function-code --function-name lf2-assignment-2 --zip-file fileb://lf2.zip
      - echo "DONE!!"
